### ISSUE TITLE
Wrong folder name in release artifact.

### ISSUE THREAD

**Issue by ahacke** [Cogito/belt-reverser#3]
Factorio version: 0.15.37
artifact-version: belt-reverser-belt-reverser_0.0.3.zip
OS: win10 x64

The folder name contained in the artifact is wrong. The folder is named `belt-reverser-belt-reverser_0.0.3`. Factorio throws a mod loading error at the start. The folder should be named `belt-reverser_0.0.3` to be loaded.

**Reproduce**
1. Download [belt-reverser-belt-reverser_0.0.3.zip](https://github.com/Cogito/belt-reverser/archive/belt-reverser_0.0.3.zip) and unzip it into the mod directory of factorio. 
1. Start the game --> get the error

**Comment by Cogito** [comment]
Well that's disappointing.

Should be fixed now, but can't test myself straight away so hopefully it works!
